export default [
    {
        _id: '62ad9353c251385de81dd6a9',
        ordering: 0,
        permissions: ['read', 'create', 'update', 'delete'],
        type: 'document',
        name: 'Activity Log',
        __v: 0,
    },
    {
        _id: '62a59311813c51ebf5e1934e',
        ordering: 0,
        permissions: ['read', 'create', 'update', 'delete'],
        type: 'document',
        name: 'Slider',
        __v: 0,
    },
    {
        _id: '6290e17df804020c2542fd91',
        ordering: 0,
        permissions: ['read', 'update', 'export'],
        type: 'document',
        name: 'Payment',
        __v: 0,
    },
    {
        _id: '6290e17df804020c2542fd92',
        ordering: 0,
        permissions: ['read', 'export'],
        type: 'document',
        name: 'Transaction',
        __v: 0,
    },
    {
        _id: '629524b186d1a224131a7f0a',
        ordering: 0,
        permissions: ['create', 'read', 'delete'],
        type: 'document',
        name: 'Order',
        __v: 0,
    },
    {
        _id: '62833e8d28a84c8490dfa925',
        ordering: 0,
        permissions: ['create', 'read', 'update', 'delete'],
        type: 'document',
        name: 'File',
        __v: 0,
    },
    {
        _id: '62809d5f71648142192a0d00',
        ordering: 0,
        permissions: ['create', 'read', 'update', 'delete', 'submit', 'approve'],
        type: 'document',
        name: 'Course',
        __v: 0,
    },
    {
        _id: '62809d5f71648142192a0d01',
        ordering: 0,
        permissions: ['create', 'read', 'update', 'delete'],
        type: 'document',
        name: 'Category',
        __v: 0,
    },
    {
        _id: '6283266b37e7d48630def28c',
        ordering: 0,
        permissions: ['create', 'read', 'update', 'delete'],
        type: 'document',
        name: 'Topic',
        __v: 0,
    },
    {
        _id: '62833a679bf73a8fb2930efc',
        ordering: 0,
        permissions: ['create', 'read', 'update', 'delete', 'reply'],
        type: 'document',
        name: 'Comment',
        __v: 0,
    },
    {
        _id: '62833a06da5e91dbe080d5ee',
        ordering: 0,
        permissions: ['create', 'read', 'update', 'delete', 'respond'],
        type: 'document',
        name: 'Review',
        __v: 0,
    },
    {
        _id: '62809d5f71648142192a0d02',
        ordering: 0,
        permissions: ['create', 'read', 'update', 'delete'],
        type: 'document',
        name: 'User',
        __v: 0,
    },
    {
        _id: '62809d5f71648142192a0d03',
        ordering: 0,
        permissions: ['create', 'read', 'update', 'delete'],
        type: 'document',
        name: 'Role',
        __v: 0,
    },
    {
        _id: '62809d5f71648142192a0d04',
        ordering: 2,
        permissions: ['access'],
        type: 'area',
        name: 'Admin control panel',
        __v: 0,
    },
    {
        _id: '62809d5f71648142192a0d05',
        ordering: 2,
        permissions: ['access'],
        type: 'area',
        name: 'Instructor control panel',
        __v: 0,
    },
    {
        _id: '628cea783e322e0c48e1d7bf',
        ordering: 1,
        permissions: ['view'],
        type: 'feature',
        name: 'Performances',
        __v: 0,
    },
    {
        _id: '628e587fa756609838b0abd4',
        ordering: 1,
        permissions: ['read', 'update'],
        type: 'feature',
        name: 'Setting',
        __v: 0,
    },
];
