import { USD_FACTOR } from './../utils/constants/app.constant';
export default [
    {
        _id: '622db7eaa2463b43c6eaa250',
        history: {
            createdAt: '2022-04-22',
            createdBy: '622c1f382e96f2828a7dae2f',
            publishedAt: '2022-04-25',
        },
        promotions: {
            enabled: false,
        },
        messages: {
            congratulations:
                "Congratulations! You are finished this class, wish you'll find a good job with high salary!",
            welcome: 'Hello, welcome you to this class!',
        },
        meta: {
            contentVideoLength: 0,
            ratingCount: 323,
            avgRatingScore: 3,
            studentCount: 0,
        },
        details: {
            suitableLearner: [
                'Anyone who wants to learn React and deepen their knowledge about coding',
                'Students who want to learn how to build reactive and fast web apps',
                'Students who want to take their web development skills to the next level and learn a future-proof technology',
            ],
            description:
                '<p><strong>This course is fully up-to-date with React 18 (the latest version of React)!</strong></p><p><br></p><p><strong>It was completely updated and re-recorded from the ground up - it teaches the very latest version of React with all the core, modern features you need to know!</strong></p><p>---</p><p>This course also comes with&nbsp;<strong>two paths</strong>&nbsp;which you can take:&nbsp;The&nbsp;<strong>"complete"&nbsp;path</strong>&nbsp;(full &gt;40h course) and the&nbsp;<strong>"summary"&nbsp;path</strong>&nbsp;(~4h summary module) - you can choose the path that best fits your time requirements!&nbsp;:-)</p><p>---</p><p>React.js is&nbsp;<strong>THE most popular JavaScript library</strong>&nbsp;you can use and learn these days to build modern, reactive user interfaces for the web.</p><p>This course teaches you React in-depth,&nbsp;<strong>from the ground up</strong>, step by step by diving into all the core basics, exploring tons of examples and also introducing you to advanced concepts as well.</p><p>You\'ll get&nbsp;<strong>all the theory, tons of examples and demos, assignments and exercises and tons of important knowledge</strong>&nbsp;that is skipped by most other resources - after all, there is a reason why this course is that huge! :)</p><p>And in case you don\'t even know why you would want to learn React and you\'re just here because of some ad or "the algorithm" - no worries: ReactJS is a key technology as a web developer and&nbsp;<strong>in this course I will also explain WHY it\'s that important</strong>!</p><p><br></p><p><strong>Welcome to "React - The Complete Guide"!</strong></p><p>This course will teach you React.js in a practice-oriented way, using all the latest patterns and best practices you need. You will learn all the key fundamentals as well as advanced concepts and related topics to turn you into a React.js developer.</p><p>This is a huge course because&nbsp;<strong>it really covers EVERYTHING you need to know and learn to become a React.js developer!</strong></p><p>No matter if you&nbsp;<strong>know nothing about React</strong>&nbsp;or if you already&nbsp;<strong>got some basic React knowledge</strong>&nbsp;(not required but also not a problem), you will get&nbsp;<strong>tons of useful information and knowledge out of this course</strong>!</p><p>My goal with this course is to ensure that you feel confident working with React, so that you can apply for React jobs, use it in your own projects or simply enhance your portfolio as a developer - whatever your goal is: This course gets you there!</p><p><br></p><p>I originally created this course in 2017 and I have kept it updated since that -&nbsp;<strong>redoing it from the ground up in 2021</strong>. And of course I\'m dedicated to keeping this course up-to-date - so that you can rely on this course to learn React in the best possible way!</p><p><strong>What\'s in this course?</strong></p><ul><li>A thorough introduction to React.js (What is it and why would you use it?)</li><li>All the core basics: How React works, building components with React &amp; building UIs with React</li><li>Components, props &amp; dynamic data binding</li><li>Working with user events and state to create interactive applications</li><li>A (thorough) look behind the scenes to understand how React works under the hood</li><li>Detailed explanations on how to work with lists and conditional content</li><li>React Hooks (in-depth)!</li><li>Working with built-in Hooks and building custom Hooks</li><li>How to debug React apps</li><li>Styling React apps with "Styled Components" and "CSS Modules"</li><li>Working with "Fragments" &amp; "Portals"</li><li>Dealing with side effects</li><li>Class-based components and functional components</li><li>Sending Http requests &amp; handling transitional states + responses</li><li>Handling forms and user input (incl. validation)</li><li>Redux &amp; Redux Toolkit</li><li>Routing with React Router</li><li>An in-depth introduction into Next.js</li><li>Deploying React Apps</li><li>Implementing Authentication</li><li>Unit Tests</li><li>Combining React with TypeScript</li><li>Adding Animations</li><li>Tons of examples and demo projects so that you can apply all the things you learned in real projects</li><li>And so much more - check out the full curriculum on this page!</li></ul><p>This really is the "Complete Guide" - promised!</p><p>And best of all?</p><p><strong>You don\'t need any prior React knowledge!</strong></p><p>This course starts with zero knowledge assumed!&nbsp;<strong>All you need is basic web development and JavaScript knowledge</strong>&nbsp;(though the course even&nbsp;<strong>includes a brief JavaScript refresher</strong>&nbsp;to ensure that we\'re all on the same page!).</p><p><strong>Check out the full curriculum, the free preview videos and join the course risk-free thanks to the 30-day money-back guarantee!</strong></p>',
            sections: [
                {
                    units: [
                        {
                            type: 'quiz',
                            quiz: '626ffd63f95b27f0cc7ab5d8',
                            _id: '626ffd63f95b27f0cc7ab5da',
                        },
                        {
                            type: 'lecture',
                            lecture: '6253d256f83c22c4839ab194',
                            _id: '6253d256f83c22c4839ab196',
                        },
                        {
                            type: 'quiz',
                            quiz: '625bc8d5307f7fb5fce202f4',
                            _id: '625bc8d5307f7fb5fce202f6',
                        },
                        {
                            type: 'lecture',
                            lecture: '6253d27af83c22c4839ab1b3',
                            _id: '6253d27af83c22c4839ab1b5',
                        },
                        {
                            type: 'lecture',
                            lecture: '6253d403f83c22c4839ab293',
                            _id: '6253d403f83c22c4839ab295',
                        },
                        {
                            type: 'lecture',
                            lecture: '6253d408f83c22c4839ab29e',
                            _id: '6253d408f83c22c4839ab2a0',
                        },
                        {
                            type: 'lecture',
                            lecture: '6253d40df83c22c4839ab2a9',
                            _id: '6253d40df83c22c4839ab2ab',
                        },
                        {
                            type: 'lecture',
                            lecture: '6253d418f83c22c4839ab2bf',
                            _id: '6253d418f83c22c4839ab2c1',
                        },
                        {
                            type: 'lecture',
                            lecture: '6253d414f83c22c4839ab2b4',
                            _id: '6253d414f83c22c4839ab2b6',
                        },
                        {
                            type: 'lecture',
                            lecture: '6253d421f83c22c4839ab2ca',
                            _id: '6253d421f83c22c4839ab2cc',
                        },
                        {
                            type: 'lecture',
                            lecture: '6253d432f83c22c4839ab2db',
                            _id: '6253d432f83c22c4839ab2dd',
                        },
                        {
                            type: 'lecture',
                            lecture: '6253d438f83c22c4839ab2e6',
                            _id: '6253d438f83c22c4839ab2e8',
                        },
                        {
                            type: 'lecture',
                            lecture: '6253d449f83c22c4839ab304',
                            _id: '6253d449f83c22c4839ab306',
                        },
                        {
                            type: 'lecture',
                            lecture: '6253d444f83c22c4839ab2f9',
                            _id: '6253d444f83c22c4839ab2fb',
                        },
                    ],
                    objective: '',
                    title: 'Morden Javascript',
                    _id: '6253d23ff83c22c4839ab185',
                },
                {
                    units: [
                        {
                            type: 'lecture',
                            lecture: '6253d4d6f83c22c4839ab3b0',
                            _id: '6253d4d6f83c22c4839ab3b2',
                        },
                        {
                            type: 'lecture',
                            lecture: '6253d4dcf83c22c4839ab3bb',
                            _id: '6253d4dcf83c22c4839ab3bd',
                        },
                        {
                            type: 'lecture',
                            lecture: '6253d4e2f83c22c4839ab3c6',
                            _id: '6253d4e2f83c22c4839ab3c8',
                        },
                        {
                            type: 'lecture',
                            lecture: '6253d4eaf83c22c4839ab3d1',
                            _id: '6253d4eaf83c22c4839ab3d3',
                        },
                        {
                            type: 'lecture',
                            lecture: '6253d4f0f83c22c4839ab3dc',
                            _id: '6253d4f0f83c22c4839ab3de',
                        },
                        {
                            type: 'lecture',
                            lecture: '6253d4f5f83c22c4839ab3e7',
                            _id: '6253d4f5f83c22c4839ab3e9',
                        },
                        {
                            type: 'lecture',
                            lecture: '6253d4fcf83c22c4839ab3f2',
                            _id: '6253d4fcf83c22c4839ab3f4',
                        },
                        {
                            type: 'lecture',
                            lecture: '6253d503f83c22c4839ab3fd',
                            _id: '6253d503f83c22c4839ab3ff',
                        },
                    ],
                    objective: '',
                    title: 'ReactJs',
                    _id: '6253d4ccf83c22c4839ab3a7',
                },
                {
                    units: [
                        {
                            type: 'lecture',
                            lecture: '6253d519f83c22c4839ab417',
                            _id: '6253d519f83c22c4839ab419',
                        },
                        {
                            type: 'lecture',
                            lecture: '6253d599f83c22c4839ab461',
                            _id: '6253d59af83c22c4839ab463',
                        },
                        {
                            type: 'lecture',
                            lecture: '6253d59ff83c22c4839ab46b',
                            _id: '6253d59ff83c22c4839ab46d',
                        },
                        {
                            type: 'lecture',
                            lecture: '6253d5a5f83c22c4839ab475',
                            _id: '6253d5a5f83c22c4839ab477',
                        },
                        {
                            type: 'lecture',
                            lecture: '6253d5abf83c22c4839ab47f',
                            _id: '6253d5abf83c22c4839ab481',
                        },
                        {
                            type: 'lecture',
                            lecture: '6253d5b1f83c22c4839ab489',
                            _id: '6253d5b1f83c22c4839ab48b',
                        },
                        {
                            type: 'lecture',
                            lecture: '6253d5b9f83c22c4839ab493',
                            _id: '6253d5b9f83c22c4839ab495',
                        },
                        {
                            type: 'lecture',
                            lecture: '6253d5bff83c22c4839ab49d',
                            _id: '6253d5bff83c22c4839ab49f',
                        },
                        {
                            type: 'lecture',
                            lecture: '6253d5c5f83c22c4839ab4a7',
                            _id: '6253d5c5f83c22c4839ab4a9',
                        },
                    ],
                    objective: '',
                    title: 'React Hooks',
                    _id: '6253d50ef83c22c4839ab408',
                },
                {
                    units: [
                        {
                            type: 'lecture',
                            lecture: '6253d5e3f83c22c4839ab4b9',
                            _id: '6253d5e3f83c22c4839ab4bb',
                        },
                    ],
                    objective: '',
                    title: 'Bonus',
                    _id: '6253d5d2f83c22c4839ab4b1',
                },
            ],
            objectives: [
                'Understand fundamental React concepts',
                'Use some of ES6/ES7 JavaScript features',
                'Use de-facto standard routing solution for React applications - React Router',
                'Maintain and organize their React code base',
            ],
            requirements: [
                'You should be fairly familiar with JavaScript, HTML and CSS',
                'JavaScript + HTML + CSS fundamentals are absolutely required',
                'ES6+ JavaScript knowledge is beneficial but not a must-have',
                'NO prior React or any other JS framework experience is required!',
            ],
        },
        basicInfo: {
            image: 'https://www.freecodecamp.org/news/content/images/size/w2000/2021/07/reactcourse.png',
            discount: 0,
            isFree: false,
            currency: 'vnd',
            level: 'beginner',
            lan: 'en',
            price: 917600,
            subtitle:
                'Learn the fundamentals of React and start your journey with this amazing library',
            slug: 'testing-course',
            title: 'Testing Course',
        },
        topics: ['622c2048add1267a9e81bb2d'],
        categories: ['622c1fa5a2de424e23bbe971', '6255171e87671dccf53fbc3c'],
        status: 'active',
        __v: 0,
    },
    {
        _id: '6274bf012d4a29055ad18b45',
        history: {
            createdAt: '2018-04-25T00:00:00.000Z',
            createdBy: '622c1f382e96f2828a7dae2f',
            publishedAt: '2022-04-27',
        },
        promotions: {
            endAt: '2023-01-31T17:00:00.000Z',
            startAt: '2022-01-31T17:00:00.000Z',
            discountPrice: 435860,
            enabled: true,
        },
        messages: {
            congratulations: '',
            welcome: '',
        },
        meta: {
            contentVideoLength: 106045,
            ratingCount: 25402,
            avgRatingScore: 4.5448484,
            studentCount: 103631,
        },
        details: {
            suitableLearner: [],
            description:
                "<p><br></p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p>Angular is one of the most popular frameworks for building client apps with HTML, CSS and TypeScript. If you want to <strong>establish yourself as a front-end or a full-stack developer,</strong> you need to learn Angular.</p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p><br></p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p>If you've been confused or frustrated jumping from one Angular 4 tutorial to another, you've come to the right place. In this course, Mosh,<strong> author of several best-selling courses on Udemy, </strong>takes you on <strong>a</strong><strong> fun and pragmatic journey to master Angular 4</strong><strong>. </strong></p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p><br></p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p>By the end of watching this course, you'll be able to: </p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<ul><li><strong>Build real client apps with Angular </strong>on your own </li><li><strong>Troubleshoot</strong> common compile-time and run-time errors</li><li>Write <strong>clean and maintainable code </strong>like a professional</li><li>Apply <strong>best practices</strong> when building Angular apps </li></ul>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p><br></p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p><br></p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p>Right from the beginning, you'll jump in and <strong>build your first Angular app within minutes</strong>. Say goodbye to boring tutorials and courses with rambling instructors and useless theories! </p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p><br></p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p>Angular 2+ has been written in TypeScript. So, in section 2, you'll<strong> learn the fundamentals of TypeScript and object-oriented programming</strong> to better understand and appreciate this powerful framework. </p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p><br></p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p>Over the next 8 hours, you'll learn the <strong>essentials of building client apps with Angular</strong>: </p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<ul><li><strong>Displaying data and handling events</strong></li><li>Building re-usable <strong>components</strong></li><li>Manipulating the DOM using <strong>directives</strong> </li><li>Formatting data using <strong>pipes</strong></li><li>Building <strong>template-driven and reactive forms </strong></li><li><strong>Consuming </strong><strong>HTTP services </strong></li><li><strong>Handling HTTP errors </strong>properly </li><li>Using <strong>Reactive Extensions</strong> and observables </li><li>Adding <strong>routing and navigation</strong></li><li>Implementing <strong>authentication and authorization</strong> using JSON Web Tokens (JWT) </li><li><strong>Deploying</strong> your applications to <strong>GitHub Pages, Firebase and Heroku</strong></li></ul>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p><br></p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p>So, if you're a busy developer with limited time and want to quickly <strong>learn how to </strong><strong>build and deploy client apps with Angular</strong>, you can stop here. </p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p><br></p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p>If you're more adventurous and want to learn more, there is far more content for you! Over the following sections, you'll learn about more advanced topics: </p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<ul><li>Building real-time, server-less apps with <strong>Firebase</strong> </li><li>Animating DOM elements using <strong>Angular animations</strong></li><li>Building beautiful UIs using <strong>Angular Material</strong></li><li>Implementing the <strong>Redux architecture </strong></li><li>Writing <strong>unit and integration tests </strong></li></ul>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p><br></p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p>All that covers just <strong>over 21 hours of high-quality content</strong>. This is equivalent to <strong>a book with more than a thousand pages</strong>! But the kind of book that every line is worth reading, not a book that you want to skim! If you have taken any of Mosh's courses before, you know he is very <strong>clear and concise </strong>in his teaching and doesn't waste a single minute of your precious time!</p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p><br></p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p>Finally, at the end of the course, you'll <strong>build and deploy a real-time e-commerce application with Angular 4, Firebase 4 and Bootstrap 4</strong>. This application exhibits patterns that you see in a lot of real-world applications:</p>\n\n\n\n\n\n<ul><li><strong>Master/detail</strong></li><li><strong>CRUD operations</strong></li><li><strong>Forms with custom validation</strong></li><li><strong>Searching, sorting and pagination</strong></li><li><strong>Authentication and authorization </strong></li><li><strong>And a lot more! </strong></li></ul>\n\n\n\n\n\n<p><br></p>\n\n\n\n\n\n<p>You'll see how Mosh creates a brand new Angular project with Angular CLI and builds this application from A to Z, step-by-step. <strong>No copy/pasting! </strong><strong>These 8.5 hours are packed with tips that you can only learn from a seasoned developer. </strong></p>\n\n\n\n\n\n<p><br></p>\n\n\n\n\n\n<p>You'll learn how to <strong>apply best practices, refactor your code and produce high quality code like a professional developer.</strong> You'll <strong>learn about Mosh's design decisions along the way and why he chooses a certain approach</strong>. What he shares with you comes from his <strong>17 years of experience</strong> as a professional software developer. </p>\n\n\n\n\n\n<p><br></p>\n\n\n\n\n\n<p><strong>You're not going to get this information in other Angular courses out there! </strong></p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p><br></p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p><br></p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p>And on top of all these, you'll get: </p>\n\n<ul><li><strong>Closed-captions generated by a human, not a computer! </strong>Currently only the first few sections have closed-captions but new captions are being added every week. </li><li><strong>Offline access: </strong>if you are traveling or have a slow connection, you can download the videos and watch them offline.</li><li><strong>Downloadable source code</strong></li></ul>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p><br></p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p><br></p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p><strong>PREREQUISITES</strong></p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p>You don't need familiarity with TypeScript or any previous versions of Angular. You're going to learn both TypeScript and Angular from scratch in this course.</p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p><br></p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p><br></p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p><strong>WHAT OTHER STUDENTS WHO HAVE TAKEN THIS COURSE SAY:</strong></p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p>\"Absolutely amazing Angular course. Mosh not only introduces key concepts behind Angular, but also pays attention to coding style and good practices. Additionally, course is contstantly enhanced and updated. Also, student questions are answered by Tim - Mosh's teaching assistant. Awesome!\" -Calvis</p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p><br></p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p>\"I am amazed of how dedicated you are in providing updates and more contents to this course. This kind of value is what define a great course and made me feel that the money is well spent. Keep it up! Furthermore, lessons are arranged and planned really carefully. This made the learning experience more seamless and exciting. Thanks Mosh!\" -Rashid Razak</p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p><br></p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p>\"This is another excellent course from the wonderful author Mosh. Thank you Mosh for your awesome course on Angular. Inspite of being a Pluralsight subscriber for the last 3 years, I have subscribed 10 out of 16 courses so far Mosh has produced in Udemy. Also I have viewed 3 of his courses in Pluralsight. That is how I got introduced to this brilliant author. This speaks about the quality of his content. Once again Thank you Mosh for all your efforts. Hope to see a Design Patterns course from you soon.\" -Dhanasekar Murugesan<br></p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p><br></p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p>\"Fantastic course, well laid out, good speed, and explains the why behind everything he does, shedding light on what's under the hood. Also, Mosh has a very practical and elegant coding style worth emulating.\" -Mack O'Meara</p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p><br></p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p>\"This is the second course I've taken with Mosh as the instructor and I've signed up for another. The quality of the audio, video, and content shows Mosh invests his time and money to create great and valuable videos. The material is relevant, up-to-date, and provides the student with the ability to succeed in the subject matter (in this case Angular). My expectations were exceeded again. I'll be taking more courses with Mosh!\" -John</p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p><br></p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p><br></p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p><br></p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p><strong>30-DAY FULL MONEY-BACK GUARANTEE</strong></p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p>This course comes with a 30-day full money-back guarantee. Take the course, watch every lecture, and do the exercises, and if you are not happy for any reasons, contact Udemy for<strong> a full refund </strong>within the first 30 days of your enrolment. <strong>All your money back, no questions asked</strong>.</p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p><br></p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p><strong><br></strong></p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p><strong>ABOUT YOUR INSTRUCTOR</strong></p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p>Mosh (Moshfegh) Hamedani is a software engineer with 17 years of professional experience. He is the author of <strong>several best selling Udemy courses</strong> with <strong>more than 120,000 students in 192 countries</strong>. He has a Master of Science in Network Systems and Bachelor of Science in Software Engineering. His students describe him as passionate, pragmatic and motivational in his teaching.</p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p><br></p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p><br></p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p><strong>So, what are you waiting for? Don't waste your time jumping from one tutorial to another. Enroll in the course and you'll build your first Angular app in less than 10 minutes!</strong></p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p><br></p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p><br></p>",
            sections: [],
            objectives: [
                'Establish yourself as a skilled professional developer',
                'Build real-world Angular applications on your own',
                'Troubleshoot common Angular errors',
                'Master the best practices',
                'Write clean and elegant code like a professional developer',
            ],
            requirements: [
                'Basic familiarity with HTML, CSS and JavaScript',
                'NO knowledge of Angular 1 or Angular 2 is required',
            ],
        },
        basicInfo: {
            image: 'https://img-c.udemycdn.com/course/240x135/1247828_32bb.jpg',
            discount: 0,
            isFree: false,
            currency: 'vnd',
            level: 'all',
            lan: 'en',
            price: 2981970.6,
            subtitle:
                'The most comprehensive Angular 4 (Angular 2+) course. Build a real e-commerce app with Angular, Firebase and Bootstrap 4',
            slug: 'the-complete-angular-course-beginner-to-advanced',
            title: 'The Complete Angular Course: Beginner to Advanced',
        },
        topics: [],
        categories: ['622c1fa5a2de424e23bbe971', '6255171e87671dccf53fbc3c'],
        status: 'active',
        __v: 0,
    },
    {
        _id: '6276332bc57e9c68a0d5d95b',
        history: {
            createdAt: '2019-12-09T00:00:00.000Z',
            createdBy: '622c1f382e96f2828a7dae2f',
            publishedAt: '2019-12-15',
        },
        promotions: {
            endAt: '2023-01-31T17:00:00.000Z',
            startAt: '2022-01-31T17:00:00.000Z',
            discountPrice: 275280,
            enabled: true,
        },
        messages: {
            congratulations: '',
            welcome: '',
        },
        meta: {
            contentVideoLength: 78146,
            ratingCount: 28565,
            avgRatingScore: 4.64863,
            studentCount: 94218,
        },
        details: {
            suitableLearner: [],
            description:
                '<p>This is a front to back JavaScript course for <em><strong>a</strong><strong>bsolutely everybody</strong></em><strong>.</strong> We start with the basic fundamentals and work our way to advanced programming WITHOUT relying on frameworks or libraries at all. You will learn a ton of pure JavaScript, whether you are a beginner or an established JS programmer. There is something for everyone...</p>\n\n<p><br></p>\n\n\n\n\n\n<p><strong><em>#### WHATS INCLUDED? ####</em></strong></p>\n\n\n\n\n\n<ul><li><strong>Basics &amp; Fundamentals:</strong> Data types, let &amp; const variables, functions, conditionals, loops, object literals, arrays, etc</li><li><strong>DOM Manipulation: </strong>Selectors, traversing the DOM, show/hide, creating &amp; removing elements, event listeners</li><li><strong>OOP:</strong> ES5 prototypes, inheritance, ES2015 classes &amp; sub-classes, constructors</li><li><strong>Async JS: </strong>Ajax &amp; XHR, Fetch API, callbacks, promises, async / await</li><li><strong>ES2015+: </strong>Arrow functions, template strings, generators, iterators, maps &amp; sets, symbols &amp; more</li><li><strong>JavaScript Patterns:</strong> Module, Factory, State, Observer, Mediator, Singleton</li><li><strong>Other: </strong>Local &amp; session storage, regular expressions, try/catch error handling</li><li><strong>10 Projects of all kinds</strong></li></ul>\n\n<p><br></p>\n\n<ul></ul>\n\n\n\n\n\n<p><br></p>\n\n\n\n\n\n<p><strong><em>#### PROJECTS ####</em></strong></p>\n\n\n\n\n\n<ol><li>Task List With Local Storage</li><li>Loan Calculator</li><li>Number Guess Game</li><li>OOP Book Listing App (ES5 Prototype &amp; ES2015 Classes Version)</li><li>Chuck Norris Joke Generator</li><li>EasyHTTP - Custom HTTP Library (3 Versions - Callbacks / Promises / Async &amp; Await)</li><li>Github Finder</li><li>WeatherJS App</li><li>Calorie Tracker (Module Pattern)</li><li>Microposts - Frontend CRUD for REST API (Webpack &amp; Babel)</li></ol>\n\n\n\n\n\n<p><br></p>',
            sections: [],
            objectives: [
                'Modular learning sections & 10 real world projects with pure JavaScript',
                'Master the DOM (document object model) WITHOUT jQuery',
                'Asynchronous programming with Ajax, Fetch API, Promises & Async / Await',
                'OOP including ES5 prototypes & ES2015 classes',
                'Learn JavaScript Patterns',
                'Regular expressions, error handling, localStorage & more',
            ],
            requirements: ['Basic HTML / CSS knowledge'],
        },
        basicInfo: {
            image: 'https://img-b.udemycdn.com/course/240x135/1463348_52a4_2.jpg',
            discount: 0,
            isFree: false,
            currency: 'vnd',
            level: 'beginner',
            lan: 'en',
            price: 1949670.5999999999,
            subtitle: 'Learn and build projects with pure JavaScript (No frameworks or libraries)',
            slug: 'modern-javascript-from-the-beginning',
            title: 'Modern JavaScript From The Beginning',
        },
        topics: [],
        categories: ['622c1fa5a2de424e23bbe971', '6255171e87671dccf53fbc3c'],
        status: 'active',
        __v: 0,
    },
    {
        _id: '62931dbc9c3f5bc5511f40ae',
        history: {
            createdAt: '2022-02-28T00:00:00.000Z',
            createdBy: '622c1f382e96f2828a7dae2f',
            publishedAt: '2022-03-03T00:00:00.000Z',
        },
        promotions: {
            endAt: '2023-01-31T17:00:00.000Z',
            startAt: '2022-01-31T17:00:00.000Z',
            discountPrice: 275280,
            enabled: true,
        },
        messages: {
            congratulations: '',
            welcome: '',
        },
        meta: {
            contentVideoLength: 63593,
            ratingCount: 2396,
            avgRatingScore: 4.729402,
            studentCount: 24507,
        },
        details: {
            suitableLearner: [],
            description:
                "<p>A website can make or break a business. That's because no matter how great the company's services or products are, without a beautiful website, it's all for nothing! That's why entrepreneurs from all over the world are looking for skilled web designers who are capable of creating awesome websites. This course will help you do just that!</p><p><strong>Prepare Yourself for a Career in Web Design by Learning the Foundations of Photoshop and the Ins-and-Outs of the Design Industry</strong>&nbsp; </p><ul><li><p>Master the principles of web design &amp; typography.&nbsp; \t</p></li><li><p>Learn to design custom graphics and beautiful icons.&nbsp; \t</p></li><li><p>Gain access to premium psd files and templates to inspire your own projects.&nbsp; \t</p></li><li><p>Discover how to work with clients and how to remain competitive in a cutting-edge industry.&nbsp; \t</p></li></ul><p><strong>Create Websites that Win Clients and Enhance Your Portfolio</strong>&nbsp; </p><p>Professional web design is in high demand, with every type of business from large corporations to small boutiques looking for web designers who can improve their online presence and build their brand. This course will teach you the skills you need to create stunning website designs using Photoshop so that you can turn your clients’ visions into reality. You will also learn how to speak with clients, decode their requests, and meet their demands.&nbsp; </p><p><strong>Contents and Overview</strong>&nbsp; </p><p>Whether you’re a beginner or an advanced web designer, you will find this course beneficial in how it blends clear, concise instruction with real world examples and hands-on exercises.&nbsp; </p><p><strong>Photoshop &amp; Web Design from A to Z<br></strong>Following the course’s simple step-by-step process, you will learn the web design principles and Photoshop skills necessary to create vivid web pages and graphics, starting with fundamental topics such as comparing different versions of Photoshop and selecting a monitor, before advancing to spacing, typography, logo design, layout, and more.&nbsp; \t</p><p><strong>Client Case Studies<br></strong>You will gain a better understanding of the realities of web design by examining real-life case studies that demonstrate what to do and what not to do when working with clients.&nbsp; \t</p><p><strong>Interactive Demos<br></strong>You will watch the creation of two websites from start to finish to gain a better understanding of the design process.&nbsp; \t</p><p><strong>Free Templates &amp; Resources<br></strong>You will gain access to an exclusive selection of psd files, a cheat sheet hotkey guide, plus lots of website templates that you can use for your own projects.&nbsp; \t</p><p>&nbsp; \t<strong>Course features:</strong>&nbsp; </p><ul><li><p>Crystal clear audio from a native English speaker</p></li><li><p>Photoshop CC was used throughout the course</p></li><li><p>Professionally edited: constant zoom in on important areas, hotkeys are shown as subtitles, repetitive techniques are slightly sped up</p></li><li><p>All lectures have the .psd presentation file attached plus a .pdf with any links that were shown in the video.</p></li></ul><p>After completing this course, you will have a solid understanding of the principles of web design and the foundations of Photoshop necessary to create cutting-edge web pages and graphics. You will also be familiar with the web design industry and the professional strategies necessary to build a client base.&nbsp; </p>",
            sections: [],
            objectives: [
                'Learn about conversion rates, bounce rates, improving sales',
                'Learn how to work with coders and succesfully handover the design',
                'Understand fantastic web design principles that can be immediately applied to any project',
                'Learn UX principles that produce immediate results',
                'Create beautiful website designs in Photoshop',
                'The differences between landing pages and standard websites',
            ],
            requirements: [
                'You need at least Photoshop CS6 and a BASIC understanding of how Photoshop works',
                'A positive attitude :)',
            ],
        },
        basicInfo: {
            image: 'https://img-b.udemycdn.com/course/240x135/352132_74cf_5.jpg',
            discount: 0,
            isFree: false,
            currency: 'vnd',
            level: 'expert',
            lan: 'en',
            price: 1949670,
            subtitle:
                'Learn UI/UX and how to create stunning website | Everything you need to know about web design in 2022 | All in Photoshop',
            slug: 'master-web-design-in-photoshop-complete-uiux-masterclass',
            title: 'Master Web Design in Photoshop: Complete UI/UX Masterclass',
        },
        topics: [],
        categories: ['625e82a09c9b04f3f624d732', '625e82ac9c9b04f3f624d73c'],
        status: 'active',
        __v: 0,
    },
    {
        _id: '62931dbc9c3f5bc5511f40af',
        history: {
            createdAt: '2020-05-16T00:00:00.000Z',
            createdBy: '622c1f382e96f2828a7dae2f',
            publishedAt: '2020-05-19T00:00:00.000Z',
        },
        promotions: {
            endAt: '2023-01-31T17:00:00.000Z',
            startAt: '2022-01-31T17:00:00.000Z',
            discountPrice: 275280,
            enabled: true,
        },
        messages: {
            congratulations: '',
            welcome: '',
        },
        meta: {
            contentVideoLength: 32657,
            ratingCount: 161,
            avgRatingScore: 4.634435,
            studentCount: 784,
        },
        details: {
            suitableLearner: [],
            description:
                "<p>Learn how to use the world's most popular application for structural Slab and foundations design </p><p>Learn the Compatibility between CSI safe and the CSI Etabs to solve a complete structural projects</p><p>Learning will be done by a simple example of learning the basics</p><p>And then a real advanced example of learning things developed in the application to be able to design any project through the application</p><p>We will Use American codes ( ACI - UBC - ASCE )</p>",
            sections: [],
            objectives: [
                'CSI SAFE 2016 structural software from A to Z ( slabs and foundations )',
                'Type of slabs',
                'Flat slab',
                'long term deflection nonlinear analysis',
                'import DXF arch plan',
                'Waffle Slab',
                'Ribbed Slab',
                'Import slab from Etabs',
                'notes and comments about slabs design',
                'Foundations modeling and design',
                'Isolated Footing Design',
                'Import reactions from Etabs',
                'Strip footing',
                'Combined Footing',
                'Raft or Mat Foundation',
                'Modeling uplift by nonlinear analysis',
                'Pile Foundation',
            ],
            requirements: ['have initial knowledge in civil engineering'],
        },
        basicInfo: {
            image: 'https://img-c.udemycdn.com/course/240x135/2418484_c0ab_5.jpg',
            discount: 0,
            isFree: false,
            currency: 'vnd',
            level: 'intermediate',
            lan: 'en',
            price: 573270,
            subtitle:
                'CSI SAFE for Slab and foundations -modeling and design- structural software from A to Z',
            slug: 'csi-safe-2016-structural-software-from-a-to-z',
            title: 'CSI SAFE 2016 structural software from A to Z',
        },
        topics: [],
        categories: ['625e82a09c9b04f3f624d732', '625e833f9c9b04f3f624d7b9'],
        status: 'active',
        __v: 0,
    },
    {
        _id: '62931dbc9c3f5bc5511f40b0',
        history: {
            createdAt: '2018-07-11T00:00:00.000Z',
            createdBy: '622c1f382e96f2828a7dae2f',
            publishedAt: '2018-07-14T00:00:00.000Z',
        },
        promotions: {
            endAt: '2023-01-31T17:00:00.000Z',
            startAt: '2022-01-31T17:00:00.000Z',
            discountPrice: 275280,
            enabled: true,
        },
        messages: {
            congratulations: '',
            welcome: '',
        },
        meta: {
            contentVideoLength: 100030,
            ratingCount: 6778,
            avgRatingScore: 4.249486,
            studentCount: 46780,
        },
        details: {
            suitableLearner: [],
            description:
                "<p>This course is a really comprehensive guide to the <strong>Google Cloud Platform - it has ~25 hours of content and ~60 demos</strong>.<br></p>\n\n<p>The Google Cloud Platform is not currently the most popular cloud offering out there - that's AWS of course - but it is possibly the best cloud offering for high-end machine learning applications. That's because TensorFlow, the super-popular deep learning technology is also from Google.</p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<p><strong>What's Included:</strong></p>\n\n\n\n<ul><li><strong>Compute and Storage</strong> - AppEngine, Container Enginer (aka Kubernetes) and Compute Engine</li><li><strong>Big Data and Managed Hadoop</strong> - Dataproc, Dataflow, BigTable, BigQuery, Pub/Sub </li><li><strong>TensorFlow</strong> on the Cloud - what neural networks and deep learning really are, how neurons work and how neural networks are trained.</li><li><strong>DevOps stuff</strong> - StackDriver logging, monitoring, cloud deployment manager</li><li><strong>Security</strong> - Identity and Access Management, Identity-Aware proxying, OAuth, API Keys, service accounts</li><li><strong>Networking</strong> - Virtual Private Clouds, shared VPCs, Load balancing at the network, transport and HTTP layer; VPN, Cloud Interconnect and CDN Interconnect</li><li><strong>Hadoop Foundations:</strong> A quick look at the open-source cousins (Hadoop, Spark, Pig, Hive and HBase)</li></ul>",
            sections: [],
            objectives: [
                'Deploy Managed Hadoop apps on the Google Cloud',
                'Build deep learning models on the cloud using TensorFlow',
                'Make informed decisions about Containers, VMs and AppEngine',
                'Use big data technologies such as BigTable, Dataflow, Apache Beam and Pub/Sub',
            ],
            requirements: [
                'Basic understanding of technology - superficial exposure to Hadoop is enough',
            ],
        },
        basicInfo: {
            image: 'https://img-b.udemycdn.com/course/240x135/1299656_ad0c.jpg',
            discount: 0,
            isFree: false,
            currency: 'vnd',
            level: 'all',
            lan: 'en',
            price: 1949670,
            subtitle: 'The Google Cloud for ML with TensorFlow, Big Data with Managed Hadoop',
            slug: 'gcp-complete-google-data-engineer-and-cloud-architect-guide',
            title: 'GCP: Complete Google Data Engineer and Cloud Architect Guide',
        },
        topics: [],
        categories: ['622c1fa5a2de424e23bbe971', '625a601faf7ad1701fe814b6'],
        status: 'active',
        __v: 0,
    },
    {
        _id: '62931dbc9c3f5bc5511f40b1',
        history: {
            createdAt: '2021-08-30T00:00:00.000Z',
            createdBy: '622c1f382e96f2828a7dae2f',
            publishedAt: '2021-09-02T00:00:00.000Z',
        },
        promotions: {
            endAt: '2023-01-31T17:00:00.000Z',
            startAt: '2022-01-31T17:00:00.000Z',
            discountPrice: 275280,
            enabled: true,
        },
        messages: {
            congratulations: '',
            welcome: '',
        },
        meta: {
            contentVideoLength: 222631,
            ratingCount: 5494,
            avgRatingScore: 4.318143,
            studentCount: 36845,
        },
        details: {
            suitableLearner: [],
            description:
                "<p><strong><em>What do you get in this course?</em></strong></p><p>In this course, you will discover the power of Android app development, and obtain the skills to <strong>dramatically increase your career prospects</strong> as a software developer. You’ll also have a head start over other developers using obsolete tools and earlier versions of Android.<br><br>Android is continually being updated and you'll learn how to target but users of current versions of Android and older versions as well.<br><br>With this course, you get the best of both worlds. You’re taught to write code for Android that works with the current version and older versions of Android by using the AppCompat library. That way, the apps you build will work with more versions of Android, giving you access to a wider audience of users.</p><p>Starting is easy because no previous programming experience is needed. <strong>NONE!</strong> If you do have it, great. Or maybe you just want to brush up on your Android development skills, and that’s fantastic too.</p><p>The course is presented using a combination of video, slides and diagrams, all designed to teach you everything you need to know.</p><p>Here is what just one student thinks about the course.</p><p>\"If you are thinking of learning how to develop an Android app, you should be doing this course. It is comprehensive and covers so many aspects of programming an Android app. The best part is that Tim explains and teaches you how to become an independent developer.    Since completing this course, I have gone on and developed my own application, which is now published on the Google Play Store! Developing an app takes patience, and it is definitely worthwhile going through all the content in this course.\" - Daniel Lee</p><p><strong>Should you write Android apps that target only the very latest version of Android?<br><br></strong>If you have an iPhone or iPad, chances are high that you update each year to the latest iOS release - most users do.</p><p>The situation is completely different with Android. Only a relatively small percentage of Android users update their phones annually.</p><p>If you write your apps to only support the latest version of Android, you will ensure 95% of your potential user base will never see your app.  The Google app store will only show apps that a users Android device can run, so if their device is not running the latest version of Android, they won't even be able to find your app on the Google play app store!</p><p><strong><em>How do you make sure your app targets older versions of Android?</em></strong></p><p>Android development is less about making sure you are creating apps that work with the latest version of Android, and more about ensuring your apps work with whatever versions of Android your users are running.</p><p>Google are aware of this problem and have something call the AppCompat library.  Which is a way for you to ensure your apps work on older devices.</p><p>This is not enabled by default.  Meaning that if you do not specifically configure your app to use this library and target older devices and newer ones, it either won't show up at all for users searching for your app, or older Android devices running your app might crash because they are trying to access features that do not exist in their version of Android.</p><p>The key is to use this library.  And that's what you will learn in this course.</p><p><strong><em>Does that mean that your apps can only use features from really old Android versions?</em></strong></p><p>No it does not.  The AppCompat library is constantly updated by Google.  They go back and add features to the library which allows older Android devices to access newer features of Android.</p><p>But again, this is not turned on by default.  You have to create and write your Android apps in a particular way to have your Android app be able to work correctly for current and older versions of Android.</p><p><strong><em>Should you learn Kotlin?</em></strong></p><p>Now that Google are pushing so hard for Android developers to use Kotlin, we are seeing a dramatic shift to Kotlin - It's similar to the iOS situation a few years ago with Objective-C when Apple released Swift.</p><p>Fast forward a few years and everyone is using Swift.  This is starting to happen with Android app development. Developers who used to use  Java are switching to Kotlin.  You can see why Google want this to happen.  They have been in court numerous times with Oracle (the owners of Java) relating to a dispute over the use of the Java language.</p><p>Google want developers to adopt Kotlin so that they don't have to worry about Java any more.</p><p>The recent Google I/O conference show mainly Kotlin code examples.  You can see where we are heading.  Kotlin is the future for Android app development.</p><p>Soon there will be few Java developers writing Android apps - they will be using Kotlin.</p><p>The good news is, we've bundled a complete Kotlin tutorial we wrote from scratch with the course.  So not only do we use Kotlin in this course (teaching best practices along the way), but we also include a complete Kotlin tutorial as well. You will learn how to use the Kotlin language in this course.</p><p><strong><em>This is what you’ll learn in the course:</em></strong></p><p>·      Develop apps for the very latest version of Android that also work on older Android devices running older versions of the Android operating system.</p><p>·      Download, install and configure the necessary (free) software.</p><p>·      Create your first app.</p><p>·      Build a range of apps demonstrating key aspects of the Android framework.</p><p>·      Test your apps on emulators or a real Android phone or tablet.</p><p>·      You’ll learn Kotlin programming because Google are recommending and pushing adoption of Kotlin for Android app development.  Included are Kotlin tutorial videos that will get you up to speed fast.</p><p>·      Ensure your apps work with current and older Android versions on phones and tablets.</p><p>·      Use Android studio 3.2, the newest version of Google's premier Android tool.</p><p>·      Learn how to use databases, web services, and even get your apps to speak!</p><p>·      Understand the all new Constraint layout, for \"drag and drop\" screen creation.</p><p>·      Use powerful libraries of code to play videos, download website data, manipulate images, and a whole lot more!</p><p>To <strong>reinforce what you’ve learnt</strong> during the course, there are numerous challenges designed to help you understand each concept being taught. You’re also shown the solution to the challenge so you know you’re always on the right track.</p><p>The course is <strong>continually updated and enhanced, and fully supported as it evolves</strong>. </p><p>With many courses, it’s just set and forget. But not with this one! We’ve got a <strong>PROVEN track record of continually updating and adding new content</strong>. An example is Tim's Java Masterclass course which now has 77 hours of content and counting, and benefited a whopping 260,000 students.</p><p>And if you have any doubts about the course, be blown away by the glowing reviews left by students on this page.</p><p><strong>What else will you learn?</strong></p><p>You will  learn how Android works at a deep level. Many courses show you how to create Android apps, allowing you to follow along clicking buttons but not really understanding what it happening.</p><p>To become a successful Android app developer, you need to understand why you are clicking that button, and how the Android operating system works and how the Android SDK and Framework works.</p><p>If you truly understand how something works, it means you can produce better quality apps, that have fewer bugs.</p><p>We don't promise that you are going to write a Facebook or Instagram clone app in this course - Courses that say they are going to teach you to create apps like that show apps with only the smallest amount of functionality, and usually don't explain anything in detail.  There is no point going through Android training unless you can take that training and apply it into your own apps.<br><br>This course is designed for you to follow along, but then to apply the information you have learned into your own apps.<br><br>Your instructors are me, Tim Buchalka and Jean-Paul Roberts. Between them theyhave a collective 70 years of commercial software development experience, <strong>meaning you’re learning the right way to program to maximize your future development potential.</strong></p><p>Here’s what’s important. There’re a lot of people teaching Android development who are not developers. We’re developers with many years’ experience with the Android platform, who also teach Android.</p><p>Importantly, our courses teach students the real-life skills needed to get those in-demand jobs or further your programming skills.</p><p>Take this course in confidence today knowing you have just found the <strong>BEST</strong> Android Kotlin course on Udemy!  Don't delay. Every minute you’re not learning Android is a missed opportunity for that PERFECT high paying job.</p><p>Click the <strong>BUY NOW</strong> button and start learning. The world needs your new apps!</p>",
            sections: [],
            objectives: [
                'Learn the core Android app development and Kotlin skills to build real Android apps.',
                'Learn how to target current and older versions of Android when writing your apps.',
                'Understand how to create Android apps using Kotlin.',
                'Be able to apply for Android app development roles.',
            ],
            requirements: [
                'A Windows computer,  a Mac, or a Linux machine so that the free Google Android Studio tool can be downloaded and install (full instructions included).',
                'An open mind to learn something new and exciting which may make a huge difference in your future career.',
                'Everything else needed to write apps for Android 8 Oreo with Kotlin is already included in the course.',
            ],
        },
        basicInfo: {
            image: 'https://img-c.udemycdn.com/course/240x135/1424326_2ee2_2.jpg',
            discount: 0,
            isFree: false,
            currency: 'vnd',
            level: 'beginner',
            lan: 'en',
            price: 1949670,
            subtitle:
                'Learn Kotlin Android App Development And Become an Android Developer.  Incl. Kotlin Tutorial and Android Tutorial Videos',
            slug: 'android-app-development-masterclass-using-kotlin',
            title: 'Android App Development Masterclass using Kotlin',
        },
        topics: [],
        categories: ['622c1fa5a2de424e23bbe971', '625e78caf55d3252cd0f78a5'],
        status: 'active',
        __v: 0,
    },
    {
        _id: '62931dbc9c3f5bc5511f40b2',
        history: {
            createdAt: '2019-09-04T00:00:00.000Z',
            createdBy: '622c1f382e96f2828a7dae2f',
            publishedAt: '2019-09-07T00:00:00.000Z',
        },
        promotions: {
            endAt: '2023-01-31T17:00:00.000Z',
            startAt: '2022-01-31T17:00:00.000Z',
            discountPrice: 275280,
            enabled: true,
        },
        messages: {
            congratulations: '',
            welcome: '',
        },
        meta: {
            contentVideoLength: 18749,
            ratingCount: 5071,
            avgRatingScore: 4.606681,
            studentCount: 26482,
        },
        details: {
            suitableLearner: [],
            description:
                "<p>Welcome to Probability and Statistics for Business and Data Science!</p><p>In this course we cover what you need to know about probability and statistics to succeed in business and the data science field!</p><p>This practical course will go over theory <strong>and</strong> implementation of statistics to real world problems. Each section has example problems, in course quizzes, and assessment tests. </p><p>We’ll start by talking about the basics of data, understanding how to examine it with measurements of central tendency, dispersion, and also building an understanding of how bivariate data sources can relate to each other.</p><p>Afterwards we’ll dive into probability , learning about combinations and permutations, as well as conditional probability and how to apply bayes theorem.</p><p>Then we’ll move on to discussing the most common distributions found in statistics, creating a solid foundation of understanding how to work with uniform, binomial, poisson, and normal distributions.</p><p>Up next we’ll talk about statistics, applying what we’ve learned so far to real world business cases, including hypothesis testing and the student's T distribution.</p><p>We’ll end the course with 3 sections on advanced topics, such as ANOVA (analysis of variance), understanding regression analysis, and finally performing chi squared analysis.</p><p>The sections are modular and organized by topic, so you can reference what you need and jump right in!</p><p>Our course includes HD Video with clear explanations and high quality animations, we also include extensive case studies to show you how to apply this knowledge to the real world.</p><p>We'll cover everything you need to know about statistics and probability to clearly tackle real world business and data science problems!</p><p>Including: </p><ul><li><p>Measurements of Data</p></li><li><p>Mean, Median, and Mode</p></li><li><p>Variance and Standard Deviation</p></li><li><p>Co-variance and Correlation</p></li><li><p>Permutations and Combinations</p></li><li><p>Unions and Intersections</p></li><li><p>Conditional Probability</p></li><li><p>Bayes Theorem</p></li><li><p>Binomial Distribution</p></li><li><p>Poisson Distribution</p></li><li><p>Normal Distribution</p></li><li><p>Sampling</p></li><li><p>Central Limit Theorem</p></li><li><p>Hypothesis Testing</p></li><li><p>T-Distribution Testing</p></li><li><p>Regression Analysis</p></li><li><p>ANOVA</p></li><li><p>Chi Squared</p></li><li><p>and much more!</p></li></ul><p>Not only do you get great technical content, but you’ll also have access to our online QA forums as well as our student chat channel. Where the TAs and myself are happy to help out with any questions you encounter! Upon finishing this course you’ll receive a certificate of completion you can post on your linkedin profile to show off to your colleagues, or even potential employers!</p><p>All of this content comes with a 30 day money back guarantee, so you can try out the course risk free!</p><p><br></p><p>So what are you waiting for? Enroll today and we'll see you inside the course!</p>",
            sections: [],
            objectives: [
                'Understand the basics of probability',
                'Be able to implement basic statistics',
                'Understand how to use various statistical distributions',
                'Apply statistical methods and hypothesis testing to business problems',
                'Understand how regression models work',
                'Implement one way and two way ANOVA',
                'Understand Chi Squared Tests',
                'Be able to understand different types of data',
            ],
            requirements: [
                'Paper and Pencil to take notes',
                'Optional: Excel or Python to run simulations',
            ],
        },
        basicInfo: {
            image: 'https://img-b.udemycdn.com/course/240x135/1673166_c2a0_4.jpg',
            discount: 0,
            isFree: false,
            currency: 'vnd',
            level: 'intermediate',
            lan: 'en',
            price: 1949670,
            subtitle:
                'Learn how to apply probability and statistics to real data science and business applications!',
            slug: 'probability-and-statistics-for-business-and-data-science',
            title: 'Probability and Statistics for Business and Data Science',
        },
        topics: [],
        categories: ['622c1fa5a2de424e23bbe971', '6255171e87671dccf53fbc3d'],
        status: 'active',
        __v: 0,
    },
    {
        _id: '62931dbc9c3f5bc5511f40b3',
        history: {
            createdAt: '2022-02-03T00:00:00.000Z',
            createdBy: '622c1f382e96f2828a7dae2f',
            publishedAt: '2022-02-06T00:00:00.000Z',
        },
        promotions: {
            endAt: '2023-01-31T17:00:00.000Z',
            startAt: '2022-01-31T17:00:00.000Z',
            discountPrice: 275280,
            enabled: true,
        },
        messages: {
            congratulations: '',
            welcome: '',
        },
        meta: {
            contentVideoLength: 105877,
            ratingCount: 81184,
            avgRatingScore: 4.62994,
            studentCount: 250227,
        },
        details: {
            suitableLearner: [],
            description:
                "<p><strong>Updated for January 2, 2021, PMP&nbsp;Exam and based on PMI's Exam Content Outline.</strong></p><p>Join the thousands of others who've completed this top-rated course and passed their PMP&nbsp;exam. You can do this!</p><p><strong>PMP® Exam Prep Seminar:&nbsp;ID 109EPSWB&nbsp;</strong></p><ul><li><ul><li><p>20 hours for technical skills</p></li><li><p>9 hours for business skills</p></li><li><p>6 hours for leadership skills</p></li></ul></li><li><p>35 PDUs / 35 contact hours for the PMP exam application</p></li><li><p>90-question pre-assessment exam</p></li><li><p>90-question end-of-course assessment exam</p></li><li><p>20-questions in each section</p></li><li><p>Assignments and discussion</p></li><li><p>Coaching sections throughout to keep you motivated - You can do this!</p></li><li><p><strong>You MUST complete all assignments and exercises to claim the 35 Contact Hours.</strong></p></li></ul><p>You need to pass the PMP exam and you need quality training that'll help you in your role as a project manager. You also want to learn from an authority in project management, in an online environment with plenty of assignments, videos, and concise explanations. This course provides 35 PDUs and is taught by project management author and expert Joseph Phillips. Joseph is the author of several project management books from McGraw-Hill, the American Management Association, and Dummies&nbsp;Press. He is certified as a PMP, PMI-ACP, ITIL, Project+, and is a Certified Technical Trainer.</p><p><strong>The 35 hours of project management education are earned by completing all of the course, the assignments, exercises, and quizzes. The Learning Management System tracks your completion of the course; if you complete all the videos, assignments, and interactive sessions, you can claim these hours for your PMP exam application or maintain your PMP certification.</strong></p><p><br></p>",
            sections: [],
            objectives: [
                'Earn 35 PDUs/Contact Hours by completing the entire course',
                'You will get all the resources you need to pass the PMI PMP certification exam.',
                'You will earn 35 exam contact hours as required by PMI',
                'You will be able to discuss the PMBOK Guide with confidence.',
                'Explain the project management processes',
                'Discuss the project management knowledge areas',
                'Demonstrate the formulas, charts, and theories of project management',
                'Calculate float for complex project network diagrams',
                'Memorize the formulas for earned value management',
                'Compare and contrast processes, knowledge areas, theories, and project management best practices',
                'Build a strong foundation in Agile project management for the new PMP exam',
                'Complete hands-on assignments and exercises',
            ],
            requirements: [
                'Participants should qualify for the PMP exam',
                'Understand fundamentals of project management',
                'Dedicated to completing this PMP Exam Prep Seminar',
                'Have a deep desire to pass the PMP exam',
            ],
        },
        basicInfo: {
            image: 'https://img-c.udemycdn.com/course/240x135/1361790_2eb7_2.jpg',
            discount: 0,
            isFree: false,
            currency: 'vnd',
            level: 'beginner',
            lan: 'en',
            price: 1949670,
            subtitle: 'PMP Exam Prep Seminar - Earn 35 PDUs by completing the entire PMP course',
            slug: 'pmp-exam-prep-seminar-complete-exam-coverage-with-35-pdus',
            title: 'PMP Exam Prep Seminar - Complete Exam Coverage with 35 PDUs',
        },
        topics: [],
        categories: ['625e7f939c9b04f3f624d66b', '625e7ff99c9b04f3f624d6bf'],
        status: 'active',
        __v: 0,
    },
    {
        _id: '628e4f6f12290ccf9d28bc55',
        history: {
            createdAt: '2022-03-16T00:00:00.000Z',
            createdBy: '622c1f382e96f2828a7dae30',
            publishedAt: '2022-03-19T00:00:00.000Z',
        },
        promotions: {
            endAt: '2023-01-31T17:00:00.000Z',
            startAt: '2022-01-31T17:00:00.000Z',
            discountPrice: 275280,
            enabled: true,
        },
        messages: {
            congratulations: '',
            welcome: '',
        },
        meta: {
            contentVideoLength: 40025,
            ratingCount: 113160,
            avgRatingScore: 4.566123,
            studentCount: 477194,
        },
        details: {
            suitableLearner: [],
            description:
                "<p>Join over 450,000&nbsp;learning student and start gaining the drawing skills you've always wanted.</p><p>The\nUltimate Drawing Course will show you how to create advanced art that\nwill stand up as professional work. This course will enhance or give\nyou skills in the world of drawing - or your money back</p><p>\nThe\ncourse is your track to obtaining drawing skills like you always knew\nyou should have! Whether for your own projects or to draw for other\npeople.</p><p>\nThis\ncourse will take you from having little knowledge in drawing to\ncreating advanced art and having a deep understanding of drawing\nfundamentals. \n</p><p>\nSo\nwhat else is in it for you?</p><p>\n<strong>You’ll\ncreate&nbsp;over\n50&nbsp;different\nprojects in this course that will take you from beginner to expert!</strong></p><p>\nYou’ll\ngain instant access to all 11 sections of the course.</p><p>\nThe\ncourse is setup to quickly take you through step by step, the process\nof drawing in many different styles. It will equip you with the\nknowledge to create stunning designs and illustration!</p><p>\n<strong>Don’t\nbelieve me? I offer you a full money back guarantee within the first\n30 days of purchasing the course.</strong></p><p>\nHere’s\nwhat you get with the course:</p><p> You’ll get access to the11&nbsp;sections of the course that will teach you the fundamentals of drawing from the ground up. The course is supported with over 11 hours of clear content that I walk you through each step of the way.</p><p>\nAll\nat your fingers tips instantly.</p><ul><li><p>\n\tThe\n\tcourse starts with the basics. You will get an in depth\n\tunderstanding of the fundamentals of drawing. Fundamentals are the\n\tmost important part of creating professional art. You will learn\n\teverything from line fundamentals all the way up to highlight and\n\tshadows. \n\t</p></li><li><p>\n\tNext\n\tyou’ll learn how perspective works and how to incorporate it into\n\tyour art. You will be learning 1, 2, and 3 point perspective.</p></li><li><p>\n\tOnce\n\tyou’ve learned perspective you are going to learn how to create\n\ttexture and apply it to your drawings.</p></li><li><p>\n\tThen\n\tyou are going to learn how to draw from life. Observing life and\n\tdrawing it is a very important skill when it comes to art.</p></li><li><p>\n\tAt\n\tthis point you’ll be ready to start drawing the human face. We\n\twill spend a whole section learning how to draw the human face from\n\tdifferent angles.</p></li><li><p>\n\tNext\n\tyou’re going to learn how to draw the human figure.</p></li><li><p>\n\tLastly\n\tyou will gain access to the bonus section where I’ll teach you how\n\tI draw animation styled characters step by step. \n\t</p></li></ul><p>\nOver\nthe 7 chapters you will learn:</p><ul><li><p>\n\tHow\n\tto draw an eye</p></li><li><p>\n\tLine\n\tfundamentals</p></li><li><p>\n\tShape\n\tand form fundamental</p></li><li><p>\n\tHow\n\tto use value and contrast \n\t</p></li><li><p>\n\tSpace\n\tand perspective</p></li><li><p>\n\tStill\n\tlife drawing \n\t</p></li><li><p>\n\tCreating\n\ttexture \n\t</p></li><li><p>\n\tDrawing\n\tthe human face</p></li><li><p>\n\tDrawing\n\tthe human figure \n\t</p></li><li><p>\n\tDrawing\n\tanimation styled art</p></li></ul><p>\nWhat\nelse will you get?</p><p> - Personal contact with me and my teacher assistant.</p><p>\n-\nLifetime access to course materials</p><p>\n-\nUnderstanding of how professional art is created</p><p>\n-\nQuizzes and exercise work sheets</p><p> This all comes under one convenient easy to use platform. Plus you will get fast, friendly, responsive support on the Udemy Q&amp;A section of the course.</p><p>\n<strong>So\nwhat are you waiting for? Sign up now and\nchange your art world today!</strong></p>",
            sections: [],
            objectives: [
                'Draw objects out of your head',
                'Draw realistic light and shadow',
                'Understand the fundamentals of art',
                'Draw perspective drawings',
                'Draw the human face and figure',
            ],
            requirements: ['Paper', 'Pencil', 'Eraser', 'Ruler', 'Motivation to learn!'],
        },
        basicInfo: {
            image: 'https://img-c.udemycdn.com/course/240x135/874012_c7f2_3.jpg',
            discount: 0,
            isFree: false,
            currency: 'vnd',
            level: 'intermediate',
            lan: 'en',
            price: 1949670,
            subtitle:
                'Learn the #1 most important building block of all art, Drawing. This course will teach you how to draw like a pro!',
            slug: 'the-ultimate-drawing-course-beginner-to-advanced',
            title: 'The Ultimate Drawing Course - Beginner to Advanced',
        },
        topics: [],
        categories: ['625e82a09c9b04f3f624d732', '625e82bb9c9b04f3f624d746'],
        status: 'active',
        __v: 0,
    },
    {
        _id: '628e4f6f12290ccf9d28bc56',
        history: {
            createdAt: '2022-04-15T00:00:00.000Z',
            createdBy: '622c1f382e96f2828a7dae30',
            publishedAt: '2022-04-18T00:00:00.000Z',
        },
        promotions: {
            endAt: '2023-01-31T17:00:00.000Z',
            startAt: '2022-01-31T17:00:00.000Z',
            discountPrice: 275280,
            enabled: true,
        },
        messages: {
            congratulations: '',
            welcome: '',
        },
        meta: {
            contentVideoLength: 65052,
            ratingCount: 92669,
            avgRatingScore: 4.669987,
            studentCount: 417618,
        },
        details: {
            suitableLearner: [],
            description:
                "<p><strong>The course has recently been remastered in Unity 2021.1. </strong></p><p>This course started as a <strong>runaway&nbsp;success on Kickstarter</strong> and has gone on to become the most popular and most watched&nbsp;Unity game development course on Udemy<strong>. </strong>The course has full&nbsp;<strong>English closed-captions throughout</strong>.</p><p>Learn how to create video games using Unity, the world-leading&nbsp;free-to-use game development tool. <strong>We start super simple </strong>so you need no prior experience of&nbsp;Unity or&nbsp;coding! With our online tutorials, you'll be amazed what you can achieve right from the first moment you start the course.&nbsp; </p><p>Benefit from our <strong>world-class support </strong>from both other students, and the GameDevtv team who are regularly engaged in the&nbsp;forums and Q&amp;A section. Go on to build several games including:</p><ul><li><p>Snow Boarder: A simple <strong>Side-Scrolling jumping game </strong>using Unity's sprite shape tool</p></li><li><p>Laser Defender:&nbsp;A <strong>Top-Down Space Shooter </strong>with enemies to shoot and dodge;</p></li><li><p>TileVania: A fast-paced classic <strong>Side-Scrolling&nbsp;Platformer </strong>using Unity's Tilemap tool;</p></li><li><p>Quiz Master: A <strong>Quiz Game </strong>that focuses on learning how to set up user interface in Unity.</p></li></ul><p>Prefer to start with 3D&nbsp;games? Check-out our sister course, the Complete C# Unity Developer 3D. Already have some Unity knowledge, and want something more challenging? Check-out our epic RPG Core Combat Creator. More interested in creating 3D models from scratch? Start with our <em>Complete Blender Creator</em> course. <strong>Our green leaf logo is a symbol of passion and quality.</strong></p><p>You will have access to a course forum where you can discuss topics on a course-wide basis, or down to the individual video. Get plugged into our communities of amazing developers on Facebook (nearly 20k), in our own TA-curated Community (17k views/day), and our student chat group (10k live at any one time). Check out our reviews to see how people love this feature.&nbsp; </p><p>The course is <strong>project-based</strong> as we believe this is the best way to learn Unity and C#. You will not just be learning dry programming concepts, but applying them immediately to real indie games as you go. All the project files will be included, as well as additional references and resources - you'll never get stuck. There are talking-head videos, powerful diagrams, quality screencasts and more.&nbsp; </p><p>Oh, and it's just <strong>bigger and better </strong>than other Unity courses you will find online. See the course&nbsp;length and the reviews.&nbsp; </p><p> For each demo game you build you will follow this process...&nbsp; </p><ul><li><p>Be challenged to build the entire game yourself.</p></li><li><p>Be shown step-by step how to build it.</p></li><li><p>Be challenged to apply, and re-apply your knowledge regularly.</p></li></ul><p>You will get full <strong>lifetime access</strong> for a single one-off fee. The creators are qualified and experienced coders and avid gamers, so are able to explain complex concepts clearly, as well as entertain along the way.&nbsp;</p><p>You will <strong>learn C#, </strong>and in turn build a solid foundation for Object Oriented Programming. By the end of the course you'll be very confident in the basics of coding and game development, and hungry to learn more.&nbsp; </p><p><strong>What this course DOESN'T cover...</strong>&nbsp; </p><p>Whereas this course is already huge, we can't possibly cover everything in that time. Here are some things we will not be covering...&nbsp; </p><ul><li><p>Performance optimization.</p></li><li><p>Editor plugins or modifications.</p></li><li><p>Physics engine modification</p></li></ul><p>Anyone who wants to learn to create games: <strong>Unity is a fantastic platform which enables you to make production-quality games.</strong> Furthermore these games can be created for Windows, MacOS, iOS, Android and Web from a single source!</p><p>If you're a complete beginner, we'll teach you all the coding and game design principles you'll need. If you're an artist, we'll teach you to bring your assets to life. If you're a coder, we'll teach you game design principles.&nbsp; </p><p><strong>Dive in and learn Unity now, you won't be disappointed!</strong></p>",
            sections: [],
            objectives: [
                'Learn C#, a powerful modern language, from scratch. No prior programming experience is necessary.',
                'Become excellent at using the Unity game engine.',
                'Build a solid foundation for game design and game development that will help you build your own games.',
                'Learn how object oriented programming works in practice.',
                'Create playable game projects - good for your portfolio, or just for your own sense of achievement.',
                'Transfer your knowledge from this course to .NET, other languages, and more.',
                'Develop highly transferable coding problem solving skills.',
                'Be part of an amazing and supportive community of people similar to you.',
            ],
            requirements: [
                'Mac or PC capable of running Unity 2019 or later.',
                'A passion and willingness to learn how to code.',
            ],
        },
        basicInfo: {
            image: 'https://img-c.udemycdn.com/course/240x135/258316_55e9_11.jpg',
            discount: 0,
            isFree: false,
            currency: 'vnd',
            level: 'all',
            lan: 'en',
            price: 1949670,
            subtitle:
                'Learn Unity in C# & Code Your First Five 2D Video Games for Web, Mac & PC. The Tutorials Cover Tilemap',
            slug: 'complete-c-unity-game-developer-2d',
            title: 'Complete C# Unity Game Developer 2D',
        },
        topics: [],
        categories: ['622c1fa5a2de424e23bbe971', '625a600eaf7ad1701fe8149d'],
        status: 'active',
        __v: 0,
    },
    {
        _id: '628e4f6f12290ccf9d28bc57',
        history: {
            createdAt: '2020-12-21T00:00:00.000Z',
            createdBy: '622c1f382e96f2828a7dae30',
            publishedAt: '2020-12-24T00:00:00.000Z',
        },
        promotions: {
            endAt: '2023-01-31T17:00:00.000Z',
            startAt: '2022-01-31T17:00:00.000Z',
            discountPrice: 275280,
            enabled: true,
        },
        messages: {
            congratulations: '',
            welcome: '',
        },
        meta: {
            contentVideoLength: 1885,
            ratingCount: 3591,
            avgRatingScore: 4.4667826,
            studentCount: 8960,
        },
        details: {
            suitableLearner: [],
            description:
                "<p>Are you an accidental project manager who has found yourself taking on project management roles without formal training? Perhaps you want to learn ways to better manage your time and deliver what was promised. You may have even heard about this methodology called Agile that is all the rave. Yet, you're tired of endless research on the Internet for answers to your questions on what Agile is all about. Seems like everyone has an opinion.</p><p>In this course, I will provide the clear cut definition of Agile and provide you with tips and hacks that you can apply and practice right away in your organization. This course is meant to empower you to grow your project management skills and have a little fun along the way!</p><p>In this course, you will learn to:</p><ul><li><p>Implement and apply Agile PM techniques to your work immediately</p></li><li><p>Identify when it’s appropriate to apply Agile</p></li><li><p>Effectively communicate and engage with stakeholders to make sure you’re meeting their needs</p></li><li><p>Deliver results that add value to the org</p></li><li><p>Integrate changes so projects reflect the stakeholders’ needs</p></li></ul><p>Agile has been trending in the project management space as a more preferred way to completing projects. This popular methodology incorporates a specific set of tools and techniques that allow for a lot more flexibility and agility on your projects.</p><p>In this interactive course, participants will have access to a fillable PDF participant resource guide with activities and reflection questions. In addition, a short assignment is incorporated into the course to help you think through the value of Agile in your project work.</p><p>Sure, there are a TON of courses on Agile that you can watch. How many of them provide a plain and simple explanation of Agile in a way that allows you to immediately understand and put it into practice? If you are still searching, look no further as I have put together a to-the-point course that uses minimal jargon and makes the content relatable to YOU.</p><p>Enroll today to enhance your Agile project management know-how and better deliver your projects to meet the needs of your customers—internally and externally.</p><p>See you in the course!</p>",
            sections: [],
            objectives: [
                'Define agile and list the benefits of this popular project management methodology',
                'Identify the key elements of agile while incorporating a case study',
                'Review how to present the idea of implementing agile to your boss and your team',
                'Explain the appropriateness of using agile methodologies in your projects',
                'Evaluate your own agility and determine how you will use agile methodologies for your future projects',
            ],
            requirements: [
                'A basic understanding of task management, foundational principles of starting a project and delivering results. Some exposure to Agile would be helpful but not required to still get the full benefits of this course.',
            ],
        },
        basicInfo: {
            image: 'https://img-c.udemycdn.com/course/240x135/3709784_5d51.jpg',
            discount: 0,
            isFree: false,
            currency: 'vnd',
            level: 'all',
            lan: 'en',
            price: 1146770,
            subtitle: 'A Crash Course in Using Agile Techniques to Get Work Done',
            slug: 'agile-project-management-in-30-minutes',
            title: 'Agile Project Management in 30 Minutes',
        },
        topics: [],
        categories: ['625e7f939c9b04f3f624d66b', '625e7ff99c9b04f3f624d6bf'],
        status: 'active',
        __v: 0,
    },
];
